"""Argument parser for janusbootctl (kept separate for file-line budgets)."""

from __future__ import annotations

import argparse
from pathlib import Path

from janusbootctl import __version__


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(prog="janusbootctl", description="JanusBoot ESP CLI")
    parser.add_argument("--version", action="version", version=f"%(prog)s {__version__}")
    parser.add_argument("--esp", type=Path, default=None, help="ESP root (default: fixtures/esp)")
    parser.add_argument("--schema-dir", type=Path, default=None, help="schema/ directory")
    sub = parser.add_subparsers(dest="command", required=True)
    sub.add_parser("validate", help="Validate settings.json and entries.json")
    get_p = sub.add_parser("get", help="Get a dotted settings key")
    get_p.add_argument("key")
    set_p = sub.add_parser("set", help="Set a dotted settings key (JSON or string)")
    set_p.add_argument("key")
    set_p.add_argument("value")
    bak = sub.add_parser("backup", help="Copy settings/entries into backup/")
    bak.add_argument("--with-nvram", action="store_true", help="Also write nvram dump stub/folder")
    bak.add_argument("--nvram-text", default=None, help="Optional NVRAM dump text to store")
    gen = sub.add_parser("generate-limine", help="Write limine.conf from JSON")
    gen.add_argument("-o", "--output", type=Path, default=None)
    theme = sub.add_parser("validate-theme", help="Validate a theme.json")
    theme.add_argument("path", type=Path)
    about = sub.add_parser("about", help="Print About (version + donate)")
    about.add_argument("--json", action="store_true", help="Emit About JSON payload")
    crash = sub.add_parser("sanitize-crash", help="Sanitize crash message/stack JSON on stdin")
    crash.add_argument("--message", default="", help="Crash message")
    crash.add_argument("--stack", default="", help="Crash stack text")
    scan_p = sub.add_parser("scan", help="Discover EFI loaders")
    scan_p.add_argument("--root", type=Path, default=None, help="ESP root to scan")
    scan_p.add_argument("--write", action="store_true", help="Write entries.json")
    scan_p.add_argument(
        "--shallow", action="store_true", help="Heuristics only (no recursive walk)"
    )
    repair_p = sub.add_parser("repair-plan", help="Print dry-run repair plan JSON")
    repair_p.add_argument("--kind", choices=("janus", "bootmgfw", "nvram", "all"), default="all")
    repair_a = sub.add_parser("repair-apply", help="Apply repair plans (confirm/dry-run)")
    repair_a.add_argument("--kind", choices=("janus", "bootmgfw", "all"), default="janus")
    repair_a.add_argument("--confirm", action="store_true")
    repair_a.add_argument("--dry-run", action="store_true")
    undo = sub.add_parser("repair-undo", help="Undo last repair via repair_history")
    undo.add_argument("--confirm", action="store_true")
    undo.add_argument("--dry-run", action="store_true")
    one = sub.add_parser("oneshot", help="Add one-shot linux entry from vmlinuz(+initrd)")
    one.add_argument("vmlinuz", type=Path)
    one.add_argument("--initrd", type=Path, default=None)
    one.add_argument("--cmdline", default="root=UUID=CHANGE_ME ro quiet")
    one.add_argument("--clear", action="store_true", help="Remove oneshot entry instead")
    theme_prev = sub.add_parser("theme-preview", help="Validate theme; optional raster preview")
    theme_prev.add_argument("theme_json", type=Path)
    theme_prev.add_argument("-o", "--output", type=Path, default=None, help="Write PNG preview")
    theme_prev.add_argument("--width", type=int, default=1920)
    theme_prev.add_argument("--height", type=int, default=1080)
    theme_prev.add_argument("--preset", choices=("1080p", "1440p", "4k"), default=None)
    theme_app = sub.add_parser("theme-apply", help="Compile theme pack onto ESP (atomic)")
    theme_app.add_argument("theme_dir", type=Path)
    theme_app.add_argument("--dry-run", action="store_true")
    shop = sub.add_parser("theme-shop", help="Browse/import local theme zip packs")
    shop.add_argument("action", choices=("list", "import"))
    shop.add_argument("path", type=Path, help="Themes dir (list) or .zip (import)")
    shop.add_argument("--dest", type=Path, default=None, help="Import destination root")
    snap = sub.add_parser("snapshot-cards", help="Calm btrfs/Timeshift card stubs")
    snap.add_argument("--root", type=Path, default=Path("/"), help="Filesystem root to probe")
    usb = sub.add_parser("usb", help="Rescue ISO → removable USB (preview default)")
    usb.add_argument("action", choices=("list", "preview", "write"))
    usb.add_argument("--iso", type=Path, default=None)
    usb.add_argument("--device", default=None, help="Device path (must be removable)")
    usb.add_argument("--model", default="mock")
    usb.add_argument("--vendor", default="mock")
    usb.add_argument("--size-bytes", type=int, default=0)
    usb.add_argument("--removable", action="store_true")
    usb.add_argument("--tran", default="")
    usb.add_argument("--system", action="store_true")
    usb.add_argument("--confirm", action="store_true")
    usb.add_argument("--tool", default="dd")
    usb.add_argument("--mock-json", type=Path, default=None, help="Mock device list JSON")
    inst = sub.add_parser("install", help="Install EFI binary + limine.conf to ESP")
    inst.add_argument("--efi", type=Path, default=None, help="Path to BOOTX64.EFI / Limine")
    inst.add_argument("--confirm", action="store_true")
    inst.add_argument("--dry-run", action="store_true", default=False)
    inst.add_argument("--plan-nvram", action="store_true", help="Print NVRAM entry plan JSON")
    gui = sub.add_parser("gui", help="Launch desktop GUI (linux|windows)")
    gui.add_argument("platform", choices=("linux", "windows"))
    return parser
