"""Generate Limine limine.conf from JanusBoot JSON (cards-path best effort)."""

from __future__ import annotations

from pathlib import Path
from typing import Any

from janusbootctl.paths import entries_path, settings_path
from janusbootctl.validate import load_json, validate_esp


def _default_index(settings: dict[str, Any], entries: list[dict[str, Any]]) -> int:
    default = settings.get("default", "saved")
    if default == "saved":
        last = settings.get("last_boot")
        default = last if isinstance(last, str) else None
    if isinstance(default, str):
        for idx, entry in enumerate(entries, start=1):
            if entry.get("id") == default:
                return idx
    return 1


def _emit_entry(lines: list[str], entry: dict[str, Any], *, indent: str = "") -> None:
    title = str(entry["title"])
    protocol = str(entry["type"])
    path = str(entry["path"])
    lines.append(f"{indent}/{title}")
    # Limine uses efi_chainload / linux / etc. Map firmware/tool to efi_chainload.
    limine_proto = protocol if protocol in {"efi_chainload", "linux"} else "efi_chainload"
    lines.append(f"{indent}    protocol: {limine_proto}")
    lines.append(f"{indent}    path: {path}")
    icon = entry.get("icon")
    if isinstance(icon, str) and icon:
        lines.append(f"{indent}    # janusboot:icon={icon}")
    lines.append("")


def generate_limine_conf(esp_root: Path, *, schemas: Path | None = None) -> str:
    """Return limine.conf text for the ESP fixture/root."""
    validate_esp(esp_root, schemas=schemas)
    settings = load_json(settings_path(esp_root))
    entries_doc = load_json(entries_path(esp_root))
    assert isinstance(settings, dict)
    assert isinstance(entries_doc, dict)
    entries = [e for e in entries_doc.get("entries", []) if isinstance(e, dict)]
    visible = [e for e in entries if not e.get("hidden")]
    hidden = [e for e in entries if e.get("hidden")]

    last = settings.get("last_boot")
    lines: list[str] = [
        "# Generated by janusbootctl — do not edit by hand",
        f"# janusboot:last-used={last if isinstance(last, str) else ''}",
        "# See themes/BOOT_UI.md for Limine honest floor vs BURG cards",
        f"timeout: {int(settings['timeout'])}",
        f"default_entry: {_default_index(settings, visible)}",
    ]
    wallpaper = settings.get("wallpaper")
    if isinstance(wallpaper, str) and wallpaper:
        lines.append(f"wallpaper: {wallpaper}")
    lines.append("")

    for entry in visible:
        _emit_entry(lines, entry)

    if hidden:
        lines.append("/More…")
        lines.append("    comment: Hidden recovery and firmware tools")
        lines.append("")
        for entry in hidden:
            _emit_entry(lines, entry, indent="    ")

    return "\n".join(lines).rstrip() + "\n"


def write_limine_conf(
    esp_root: Path,
    output: Path | None = None,
    *,
    schemas: Path | None = None,
) -> Path:
    from janusbootctl.paths import janus_dir

    text = generate_limine_conf(esp_root, schemas=schemas)
    target = output or (janus_dir(esp_root) / "limine.conf")
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(text, encoding="utf-8")
    return target
