"""Generate Limine limine.conf from JanusBoot JSON."""

from __future__ import annotations

from pathlib import Path
from typing import Any

from janusbootctl.paths import entries_path, settings_path
from janusbootctl.validate import load_json, validate_esp


def _default_index(settings: dict[str, Any], entries: list[dict[str, Any]]) -> int:
    default = settings.get("default", "saved")
    if default == "saved":
        last = settings.get("last_boot")
        if isinstance(last, str):
            default = last
        else:
            return 1
    for idx, entry in enumerate(entries, start=1):
        if entry.get("id") == default:
            return idx
    return 1


def generate_limine_conf(esp_root: Path, *, schemas: Path | None = None) -> str:
    """Return limine.conf text for the ESP fixture/root."""
    validate_esp(esp_root, schemas=schemas)
    settings = load_json(settings_path(esp_root))
    entries_doc = load_json(entries_path(esp_root))
    assert isinstance(settings, dict)
    assert isinstance(entries_doc, dict)
    entries = [e for e in entries_doc.get("entries", []) if isinstance(e, dict)]
    visible = [e for e in entries if not e.get("hidden")]

    lines: list[str] = [
        "# Generated by janusbootctl — do not edit by hand",
        f"timeout: {int(settings['timeout'])}",
        f"default_entry: {_default_index(settings, visible)}",
    ]
    wallpaper = settings.get("wallpaper")
    if isinstance(wallpaper, str) and wallpaper:
        lines.append(f"wallpaper: {wallpaper}")
    lines.append("")

    for entry in visible:
        title = str(entry["title"])
        protocol = str(entry["type"])
        path = str(entry["path"])
        lines.append(f"/{title}")
        lines.append(f"    protocol: {protocol}")
        lines.append(f"    path: {path}")
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def write_limine_conf(
    esp_root: Path,
    output: Path | None = None,
    *,
    schemas: Path | None = None,
) -> Path:
    from janusbootctl.paths import janus_dir

    text = generate_limine_conf(esp_root, schemas=schemas)
    target = output or (janus_dir(esp_root) / "limine.conf")
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(text, encoding="utf-8")
    return target
